### ISSUE TITLE
Notes attachment won't open from CRM

### ISSUE THREAD

**Issue by kjtest** [anilvem1/LAMoveCRMAttachmentsToBlob-API#1]
The notes app is installed & running. It creates the blob correctly and there are no errors on any step, but when you try to open the attachment from CRM it gives an error: 

Can not open
This attachment can not be opened on your device.
Error code: 0x8005f20cSession Id: b34c962e-750c-4d82-a253-19e25a3e135eActivity Id: 400e611e-957e-458c-b837-c344585be22fTime: Mon Mar 18 2019 14:39:18 GMT+0200 (Eastern European Standard Time). 

Do you have any insight what could be wrong?

**Comment by anilvem1** [comment]
Hi,

Did you setup Attachment management solution from AppSource correctly? Did you setup the Azure Blob setting (SAS key etc) correctly in CRM so that it can talk to the correct Blob container while retrieving the attachments?

**Comment by kjtest** [comment]
Hi,
Sorry, it works ok now. It was my own mistake, I had left some of the processing steps disabled in CRM.
Thanks a lot.

**Comment by Likhithanidimusali** [comment]
> Hi,
> Sorry, it works ok now. It was my own mistake, I had left some of the processing steps disabled in CRM.
> Thanks a lot.

Hi, Can you please tell me how did you solve this issue. It happens to me also.
